FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

# Instalar Python e pip (se não vier instalado)
RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app

COPY rag-server/requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY rag-server/ .

EXPOSE 5000
CMD ["python3", "app.py"]
